### ISSUE TITLE
Filtering parameters and filtered vcfs

### ISSUE THREAD

**Issue by alvinwt** [friend1ws/nanomonsv#10]
Hi, nanomonsv is quite a very useful SV caller for paired tumour-normal samples. I am wondering if you can included the default filtering parameters in the README, i.e. number of reads required and other filters used to generate the results files. 

I would like to compare nanomonsv with other long read callers and I am wondering how to obtain a vcf with merged SV types after filtering. Currently I am able to compare the vcfs after converting bed files but not the results file back to a vcf.

**Comment by davidebolo1993** [comment]
Agree, @friend1ws would it be possible to output a valid VCF instead of that .txt ?

Thanks,

Davide

**Comment by friend1ws** [comment]
Thank you all for the interest in our software. I would like to modify nanomonsv to generate VCF format soon. Also, I will provide some scripts which we use for filtering nanomosnv result.

**Comment by friend1ws** [comment]
Sorry for the delay, I provided filtering script for nanomonsv result. 
https://github.com/friend1ws/nanomonsv/wiki/nanomonsv_filter
Hope this is helpful to you. I will also add vcf converter script soon.

**Comment by friend1ws** [comment]
I decided that in the next version, the default output format of nanomonsv will be VCF. So for VCF format please wait for a while (maybe in a month).

**Comment by davidebolo1993** [comment]
Thanks. It would be nice if you could make the VCF file compatible with Truvari (https://github.com/spiralgenetics/truvari) !

**Comment by davidebolo1993** [comment]
Hi @friend1ws, any updates on this?

Thanks,

Davide

**Comment by friend1ws** [comment]
Hi @davidebolo1993,

Thanks. The current commit can produce VCF files. I guess it will work fine. But I would like to perform further check before release.

**Comment by davidebolo1993** [comment]
Yep, let me know when it's done !

Thanks a lot !

Davide

**Comment by friend1ws** [comment]
I will try to release at least the beta version on this weekend.

**Comment by friend1ws** [comment]
Hi @davidebolo1993,

Sorry for the delay. I pre-released version 0.4.0b1.
https://github.com/friend1ws/nanomonsv/releases/tag/v0.4.0b1

I'm happy if you could try it.
For that, please download the source file from the above URL and install it manually (since it is still not in the PyPI).

**Comment by davidebolo1993** [comment]
Hi @friend1ws,

thanks. I'll give this a try today, tomorrow at the latest, and let you know.

Best,

Davide

**Comment by friend1ws** [comment]
Hi @davidebolo1993,
One thing to note is I basically recommend using the --use_racon option (for this, please install racon and add the path to the binary). This will improve the polishing of inserted sequences and breakpoint identification.

**Comment by davidebolo1993** [comment]
Thanks, I'll let you know

**Comment by davidebolo1993** [comment]
Hi @friend1ws,

Just for testing, I've tried nanomonsv on a 5X nanopore BAM subsampled from NA24385 (without matched control). The parse step worked just fine. However, I got an error at the end of the get step:

``` bash
02/24/2021 08:26:29 - nanomonsv.run - INFO - Clustering rearrangement type supporting reads for putative SVs
02/24/2021 08:26:29 - nanomonsv.run - INFO - Clustering insertion type supporting reads for putative SVs
02/24/2021 08:27:57 - nanomonsv.run - INFO - Clustering deletion type supporting reads for putative SVs
02/24/2021 08:28:46 - nanomonsv.run - INFO - Gathering sequences of supporting reads
02/24/2021 08:40:15 - nanomonsv.run - INFO - Generate consensus sequences
02/24/2021 09:09:17 - nanomonsv.run - INFO - Locating single-base resolution break points for candidate SVs
02/24/2021 22:06:51 - nanomonsv.run - INFO - Counting the number of supprting read for the tumor by realignment of SV candidate segments
02/25/2021 11:55:55 - nanomonsv.run - INFO - Final processing
Traceback (most recent call last):
  File "/home/davideb/miniconda3/bin/nanomonsv", line 33, in <module>
    sys.exit(load_entry_point('nanomonsv==0.4.0b1', 'console_scripts', 'nanomonsv')())
  File "/home/davideb/miniconda3/lib/python3.8/site-packages/nanomonsv-0.4.0b1-py3.8.egg/nanomonsv/__init__.py", line 9, in main
  File "/home/davideb/miniconda3/lib/python3.8/site-packages/nanomonsv-0.4.0b1-py3.8.egg/nanomonsv/run.py", line 242, in get_main
  File "/home/davideb/miniconda3/lib/python3.8/site-packages/nanomonsv-0.4.0b1-py3.8.egg/nanomonsv/vcf_convert.py", line 89, in genomesv2vcf_convert
  File "pysam/libcfaidx.pyx", line 290, in pysam.libcfaidx.FastaFile.fetch
  File "pysam/libcutils.pyx", line 252, in pysam.libcutils.parse_region
ValueError: start out of range (-1)
```

From the traceback, I'm pretty sure this is related to VCF generation. Also, I noticed that the entire get process is a little bit slow (> 24 hours for a 5X BAM). Any chance this can be accelerated by using multiple cores?

Thanks,

Davide

**Comment by friend1ws** [comment]
@davidebolo1993 Thank you very much for the feedback. I think the error is that SV on the edge of the chromosome got failed to be converted to VCF format. If possible, could you send the record whose value of Pos_1 or Pos_2 in the nanomonsv.result.txt file is 1 or 0 if any?

nanomonsv first extract rough candidate of SVs and then perform many validations for each of them. This validation step is mostly independent. So there is a great chance that we can accelerate the software by adding multithreading functions. I would like to add them in the future release. Also, if you add paired control data, the candidate is filtered with the control to some extent and the computational time will be reduced much.

**Comment by davidebolo1993** [comment]
Sure. I'm currently re-generating those data as I previously run nanomonsv in a snakemake pipeline that removed the output folder upon error. 
Talk to you soon,

Davide

**Comment by davidebolo1993** [comment]
Hi @friend1ws,

Here you are:

```bash
tail -n+2 GM24385.nanomonsv.result.txt | awk 'FS=OFS="\t"''{if ($2 == "0" || $2 == "1"|| $5 == "0" || $5 == "1") print}'
17	1	-	hs37d5	17257014	-	---	r_223	7	4	PASS
7	142048195	+	hs37d5	1	-	AC	r_537	9	7	PASS
GL000195.1	1	-	hs37d5	10602420	+	---	r_612	24	17	PASS
GL000214.1	1	-	hs37d5	5385914	-	G	r_620	16	2	PASS
GL000237.1	1	-	hs37d5	9509111	+	AATTAGCCGGGCATGGTAGCATGCCTGTAATCCCAGCTACTTGGGAGGCTAAGACAGGAGAACCACTT	r_629	18	8	PASS
MT	1	-	MT	16609	+	---	r_671	119	80	PASS
NC_007605	1	-	NC_007605	171863	+	---	r_673	56	33	PASS
```
I can share the entire result folder by email, if needed.

Thanks,

Davide

**Comment by friend1ws** [comment]
@davidebolo1993 Thanks! Could you please send me the GM24385.nanomonsv.result.txt file?

**Comment by davidebolo1993** [comment]
Sure !


[GM24385.nanomonsv.result.txt](https://github.com/friend1ws/nanomonsv/files/6054870/GM24385.nanomonsv.result.txt)

**Comment by friend1ws** [comment]
Thanks. It seems that the current converter program got error for the following "circular events".
```
MT	1	-	MT	16609	+	---	r_671	119	80	PASS
```
Currently, these circular events are treated as duplication.
Since duplication in the VCF record needs the reference sequence base just before the breakpoint, the program got an error trying to extract the base of 0 coordinate.

For now, I modified the program so that it treats the above cases as "breakends".
The modified program could successfully convert the GM24385.nanomonsv.result.txt.

But I will test our program further and will let you know when ready

**Comment by friend1ws** [comment]
@davidebolo1993 Sorry for the delay. During fixing the VCF conversion issues, I spotted several additional vulnerabilities and took a little time to fix them. Now, I think many of the concerns got fixed and pre-released version 0.4.0b2.

**Comment by davidebolo1993** [comment]
Hi @friend1ws,

The analysis completed without errors (still quite slow, BTW). I'm by now running nanomonsv on samples at higher coverage and I'll let you know if I get into something weird. 

Thanks,

Davide

**Comment by friend1ws** [comment]
Hi @davidebolo1993,
Great! I was mostly using tumor and matched control data for evaluation. But this time, I realized that nanomosv without matched pairs is slow. I will add multi-threading on the next version (probably 0.5.0).

**Comment by davidebolo1993** [comment]
Great, 

talk to you soon ! Thanks,

Davide

**Comment by davidebolo1993** [comment]
Hi @friend1ws,

not sure this is is an error, but maybe you want to have a look by yourself. While running on BAM files from NGMLR (generate consensus step), nanomonsv (but I guess this is a non-0 exit status from RACON) encounter an issue. This is the stdout from my snakemake job.


```
[Mon Mar 15 08:59:58 2021]
rule nanomonsv_call_total_ngmlr:
    input: data/hs37d5.fa, alignments/GM24385.ngmlr.srt.bam, alignments/GM24385.ngmlr.srt.bam.bai
    output: results/ngmlr/nanomonsv/total/GM24385.vcf
    log: logs/results/ngmlr_nanomonsv_total_call.log
    jobid: 30


[Mon Mar 15 08:59:58 2021]
rule nanomonsv_call_35X_minimap2:
    input: data/hs37d5.fa, alignments/35X/GM24385.minimap2.srt.bam, alignments/35X/GM24385.minimap2.srt.bam.bai
    output: results/minimap2/nanomonsv/35X/GM24385.vcf
    log: logs/results/minimap2_nanomonsv_35X_call.log
    jobid: 13


[Mon Mar 15 08:59:58 2021]
rule nanomonsv_call_25X_ngmlr:
    input: data/hs37d5.fa, alignments/25X/GM24385.ngmlr.srt.bam, alignments/25X/GM24385.ngmlr.srt.bam.bai
    output: results/ngmlr/nanomonsv/25X/GM24385.vcf
    log: logs/results/ngmlr_nanomonsv_25X_call.log
    jobid: 26


[Mon Mar 15 08:59:58 2021]
rule nanomonsv_call_35X_ngmlr:
    input: data/hs37d5.fa, alignments/35X/GM24385.ngmlr.srt.bam, alignments/35X/GM24385.ngmlr.srt.bam.bai
    output: results/ngmlr/nanomonsv/35X/GM24385.vcf
    log: logs/results/ngmlr_nanomonsv_35X_call.log
    jobid: 28


[Mon Mar 15 08:59:58 2021]
rule nanomonsv_call_total_minimap2:
    input: data/hs37d5.fa, alignments/GM24385.minimap2.srt.bam, alignments/GM24385.minimap2.srt.bam.bai
    output: results/minimap2/nanomonsv/total/GM24385.vcf
    log: logs/results/minimap2_nanomonsv_total_call.log
    jobid: 15

03/15/2021 11:02:03 - nanomonsv.run - INFO - Clustering rearrangement type supporting reads for putative SVs
03/15/2021 11:02:27 - nanomonsv.run - INFO - Clustering insertion type supporting reads for putative SVs
03/15/2021 11:03:49 - nanomonsv.run - INFO - Clustering deletion type supporting reads for putative SVs
03/15/2021 11:05:06 - nanomonsv.run - INFO - Gathering sequences of supporting reads
03/15/2021 11:29:02 - nanomonsv.run - INFO - Clustering rearrangement type supporting reads for putative SVs
03/15/2021 11:29:07 - nanomonsv.run - INFO - Clustering insertion type supporting reads for putative SVs
03/15/2021 11:45:53 - nanomonsv.run - INFO - Clustering deletion type supporting reads for putative SVs
03/15/2021 11:54:34 - nanomonsv.run - INFO - Gathering sequences of supporting reads
03/15/2021 11:57:44 - nanomonsv.run - INFO - Clustering rearrangement type supporting reads for putative SVs
03/15/2021 11:58:24 - nanomonsv.run - INFO - Clustering insertion type supporting reads for putative SVs
03/15/2021 12:00:30 - nanomonsv.run - INFO - Clustering deletion type supporting reads for putative SVs
03/15/2021 12:02:27 - nanomonsv.run - INFO - Gathering sequences of supporting reads
03/15/2021 12:12:05 - nanomonsv.run - INFO - Clustering rearrangement type supporting reads for putative SVs
03/15/2021 12:12:11 - nanomonsv.run - INFO - Clustering insertion type supporting reads for putative SVs
03/15/2021 12:31:12 - nanomonsv.run - INFO - Clustering rearrangement type supporting reads for putative SVs
03/15/2021 12:31:35 - nanomonsv.run - INFO - Generate consensus sequences
03/15/2021 12:32:03 - nanomonsv.run - INFO - Clustering insertion type supporting reads for putative SVs
03/15/2021 12:34:48 - nanomonsv.run - INFO - Clustering deletion type supporting reads for putative SVs
03/15/2021 12:36:02 - nanomonsv.run - INFO - Clustering deletion type supporting reads for putative SVs
03/15/2021 12:37:17 - nanomonsv.run - INFO - Gathering sequences of supporting reads
03/15/2021 12:48:13 - nanomonsv.run - INFO - Gathering sequences of supporting reads
03/15/2021 13:41:06 - nanomonsv.run - INFO - Generate consensus sequences
03/15/2021 14:16:01 - nanomonsv.run - INFO - Generate consensus sequences
03/15/2021 14:50:49 - nanomonsv.generate_consensus - WARNING - Command '['racon', '-u', 'results/ngmlr/nanomonsv/25X/GM24385.consensus_seq.txt.tmp_dir/hs37d5,31871109,31871129,+,hs37d5,31871110,31871130,-,i,20867.supporting_read.fa', 'results/ngmlr/nanomonsv/25X/GM24385.consensus_seq.txt.tmp_dir/hs37d5,31871109,31871129,+,hs37d5,31871110,31871130,-,i,20867.parasail.paf', 'results/ngmlr/nanomonsv/25X/GM24385.consensus_seq.txt.tmp_dir/hs37d5,31871109,31871129,+,hs37d5,31871110,31871130,-,i,20867.tmp.seg.first.fa']' returned non-zero exit status 1.
03/15/2021 14:56:21 - nanomonsv.run - INFO - Locating single-base resolution break points for candidate SVs
03/15/2021 14:58:51 - nanomonsv.run - INFO - Generate consensus sequences
03/15/2021 15:11:29 - nanomonsv.run - INFO - Generate consensus sequences
03/15/2021 17:50:50 - nanomonsv.generate_consensus - WARNING - Command '['racon', '-u', 'results/ngmlr/nanomonsv/35X/GM24385.consensus_seq.txt.tmp_dir/hs37d5,31871109,31871129,+,hs37d5,31871110,31871130,-,i,26256.supporting_read.fa', 'results/ngmlr/nanomonsv/35X/GM24385.consensus_seq.txt.tmp_dir/hs37d5,31871109,31871129,+,hs37d5,31871110,31871130,-,i,26256.parasail.paf', 'results/ngmlr/nanomonsv/35X/GM24385.consensus_seq.txt.tmp_dir/hs37d5,31871109,31871129,+,hs37d5,31871110,31871130,-,i,26256.tmp.seg.first.fa']' returned non-zero exit status 1.
03/15/2021 17:57:47 - nanomonsv.run - INFO - Locating single-base resolution break points for candidate SVs
03/15/2021 17:58:12 - nanomonsv.run - INFO - Locating single-base resolution break points for candidate SVs
03/15/2021 19:40:00 - nanomonsv.generate_consensus - WARNING - Command '['racon', '-u', 'results/ngmlr/nanomonsv/total/GM24385.consensus_seq.txt.tmp_dir/hs37d5,31871109,31871129,+,hs37d5,31871110,31871130,-,i,29631.supporting_read.fa', 'results/ngmlr/nanomonsv/total/GM24385.consensus_seq.txt.tmp_dir/hs37d5,31871109,31871129,+,hs37d5,31871110,31871130,-,i,29631.parasail.paf', 'results/ngmlr/nanomonsv/total/GM24385.consensus_seq.txt.tmp_dir/hs37d5,31871109,31871129,+,hs37d5,31871110,31871130,-,i,29631.tmp.seg.first.fa']' returned non-zero exit status 1.
03/15/2021 19:49:01 - nanomonsv.run - INFO - Locating single-base resolution break points for candidate SVs
03/15/2021 20:31:02 - nanomonsv.run - INFO - Locating single-base resolution break points for candidate SVs
```
 This is not happening on the other 2 BAM files from minimap2.

**Comment by friend1ws** [comment]
@davidebolo1993 Thanks. It seems this happens on just one record and did not cause significant problems. But since most of our evaluations re performed on minimap2, I will check further on the performance for NGMLR.

**Comment by davidebolo1993** [comment]
@friend1ws, that's also what I noticed, but just wanted to be on the safe side.

Thanks,

Davide

**Comment by davidebolo1993** [comment]
Hi @friend1ws,

I got into another issue while running. So it seems that for my high-coverage germline BAM files (30X or higher, both minimap2 and NGMLR) nanomonsv fails to generate both the result file and, of course, the VCF, with no specific error (it simply stopped at some point). This is not happening for lower-coverage BAM (for instance, it worked fine on a 15X BAM). 
Of course, I can share one ore more folders !

Best,

Davide

**Comment by friend1ws** [comment]
Hi, @davidebolo1993 

Thank you very much for the feedback!
I think I want to close this thread, so could you open another issue with more detailed logging info.
Also, if your data is from public data, then please let me know which data you used so that I can try by myself.

**Comment by davidebolo1993** [comment]
Hi @friend1ws,

sorry for being late on this. Data are from NA24385 ultra-long nanopore runs. An overview of the analysis pipeline is given [here](https://github.com/davidebolo1993/EViNCe). If you prefer not to use Snakemake, you can download data as described [here](https://github.com/davidebolo1993/EViNCe/blob/main/NA24385/workflow/scripts/getdata.sh) and just go on with a standard alignment pipeline with minimap2/ngmlr. I'm closing this for now.  

Thanks,

Davide

**Comment by friend1ws** [comment]
@davidebolo1993 Thanks.
