### ISSUE TITLE
The minimum normal variant read

### ISSUE THREAD

**Issue by charliechen912ilovbash** [friend1ws/nanomonsv#16]
Hi,
I am wondering that is there a 'minimum normal variant read' for `nanomonsv get` ?
there is a minimum value for tumor but there seems not for normal. 
Is the minimum normal supporting read number set to zero?
Thank you very much.

**Comment by friend1ws** [comment]
Thank you very much for the question.
There are options, `--max_control_variant_read_num` and `--max_control_VAF` whose default values are set to 1 and 0.03 in the `nanomonsv get` command.

**Comment by charliechen912ilovbash** [comment]
Thanks for the reply, but I meant is there '**minimum**' normal read number in the program?

**Comment by friend1ws** [comment]
Yes. minimum normal read number is zero.

**Comment by charliechen912ilovbash** [comment]
Sorry about bothering again, could you explain a little more about "normal read number is zero" ?
I am a little confused about it because if there is no any supporting read in normal, isn't it somatic SV instead of germline SV ?

**Comment by charliechen912ilovbash** [comment]
Sorry about bothering again, could you explain a little more about "normal read number is zero" ?
I am confused about it because if there is no any supporting read in normal, isn't it somatic SV instead of germline SV ?
For an example, if there are 3 sup read in tumor support one deletion, and there is 0 sup read in normal.

**Comment by friend1ws** [comment]
This software is basically designed for detecting somatic SVs. So nanomonsv basically require tumor and normal BAMs. For each candidate SV, nanomonsv count the supporting read numbers for the SV in tumor and normal BAMs, respectively. If the supporting reads were observed specifically in tumor BAMs, then this is considered to be somatic and will be "identified". Basically, for genuine somatic SVs, the numbers of supporting read numbers in the normal BAM are expected to be zero (in default, 1 is also allowed just in case).

**Comment by charliechen912ilovbash** [comment]
I understood. Thank you very much for the explanation.
