### ISSUE TITLE
No space left on device

### ISSUE THREAD

**Issue by charliechen912ilovbash** [friend1ws/nanomonsv#17]
Hi, I am trying with `v0.4.0` `get` command, and it showed the `No space left on device` error message,
but there are still ~10 Tb left in the disk. I am not sure the reason of this error, maybe it is because there are too many small files then inode space was fulled?
My optional parameters are: `nanomonsv get --use_racon  --min_tumor_variant_read_num 1`

```
ESC[0m11/04/2021 17:37:37 - nanomonsv.run - INFO - Clustering rearrangement type supporting reads for putative SVs
11/04/2021 17:50:51 - nanomonsv.run - INFO - Clustering insertion type supporting reads for putative SVs
11/04/2021 17:58:42 - nanomonsv.run - INFO - Clustering deletion type supporting reads for putative SVs
11/04/2021 18:10:09 - nanomonsv.run - INFO - Gathering sequences of supporting reads
11/04/2021 19:03:30 - nanomonsv.run - INFO - Generate consensus sequences
Traceback (most recent call last):
  File "/bins/miniconda3/envs/sing/bin/nanomonsv", line 8, in <module>
    sys.exit(main())
  File "/bins/miniconda3/envs/sing/lib/python3.6/site-packages/nanomonsv/__init__.py", line 9, in main
    args.func(args)
  File "/bins/miniconda3/envs/sing/lib/python3.6/site-packages/nanomonsv/run.py", line 207, in get_main
    use_racon = args.use_racon, debug = args.debug)
  File "/bins/miniconda3/envs/sing/lib/python3.6/site-packages/nanomonsv/generate_consensus.py", line 329, in generate_consensus
    consensus_generator.initialize(tkey)
  File "/bins/miniconda3/envs/sing/lib/python3.6/site-packages/nanomonsv/generate_consensus.py", line 43, in initialize
    self.temp_support_read_file_h = open(self.tmp_dir + '/' + self.temp_key + ".supporting_read.fa", 'w')
OSError: [Errno 28] No space left on device: 'nanomonsv/sample-T.consensus_seq.txt.tmp_dir/chr3,187707944,187707984,-,chr4,49711905,49711945,+,r,1250396.supporting_read.fa'
```

**Comment by friend1ws** [comment]
Thank you very much for the feedback!
How many files are there in the `nanomonsv/sample-T.consensus_seq.txt.tmp_dir` directory?
Also, are you using singularity or docker? 
If the number of intermediate files is not that much, I guess this is related to the container issue.

**Comment by charliechen912ilovbash** [comment]
Yes, I installed nanomonsv in singularity container.
I tried minimum tumor variant read

**Comment by friend1ws** [comment]
Thanks. I guess this is related to the setting of singularity? If you set `--debug` option. All the intermediate files will be kept.

**Comment by charliechen912ilovbash** [comment]
I see, I will try to fix the singularity issue. Thank you very much.
By the way, it will be much easier to use if users can install `nanomonsv` and its dependancies through `conda`
