### ISSUE TITLE
supporting read ID not included in output

### ISSUE THREAD

**Issue by charliechen912ilovbash** [friend1ws/nanomonsv#19]
I am using version 0.4.0, the `*.nanomonsv.supporting_read.txt` seems does not include any supporting read IDs.
Version 0.2.0 did include the read IDs though.

**Comment by jaesvi** [comment]
Hi, I wanted to ask if there is any progress regarding this.
Thanks.

**Comment by friend1ws** [comment]
Thank you very much. I will fix this problem in the next version, which will soon released.

**Comment by jaesvi** [comment]
Hi, congratulations on your publication. To follow-up on this issue, I see that in the publication you extract the SV-supporting reads and assign them to a specific Whatshap haplotag:
_Supporting reads for each SV were extracted and annotated using the haplotype tag in the WhatsHap results._
Could you clarify how do you do this when Nanomonsv does not provide the SV-supporting reads? 
Thanks.

**Comment by friend1ws** [comment]
Thank you very much!. I think they used version 0.2.0, which generated supporting read files with read IDs. From version 0.4.0, somehow the read ID information disappeared.... I have fixed this bug and the new release will be hopefully in couple of days.

**Comment by jaesvi** [comment]
Ah that would explain, sorry. I had not tried nanomonsv before 0.4.0 . Thanks!

**Comment by friend1ws** [comment]
We have released v0.5.0, which should solve the above problem.

**Comment by jaesvi** [comment]
Nice! How do you install the new version though? It is not (yet) on pip.

**Comment by friend1ws** [comment]
Sorry, we had some trouble pushing pypi. I think we fixed that. So please try. I am aware the current version still has several small problems and we will soon fix that.
