### ISSUE TITLE
position of insertion

### ISSUE THREAD

**Issue by charliechen912ilovbash** [friend1ws/nanomonsv#20]
Hello,
I observed some insertion output record look like the following:
`chr1    27087079        +       chr1    27087116        -      `
Could you explain why the distance between the start and the end is more than 1 ?

**Comment by friend1ws** [comment]
Sometimes, insertion and deletion can occur simultaneously. And current nanomonsv can identify these complex SVs only when the deletion is not so large (e.g. ~30bp?). And I would like to tune the algorithm so that it can identify even broader cases.
