### ISSUE TITLE
More than 1 controls?

### ISSUE THREAD

**Issue by AhmedArslan** [friend1ws/nanomonsv#21]
Hi,
I wanted to know, what if I have more than 1 sample and 1 controls, can we compare them simultaneously, in the same run? 
Thanks.

**Comment by friend1ws** [comment]
If the samples are from the same individual, then you can merge the "case" bam files (as tumor) and the "control" bam files and perform nanomonsv as usual.

**Comment by AhmedArslan** [comment]
so, multi case-control comparison is not possible, (simultaneously) in one run?

**Comment by friend1ws** [comment]
Currently, we do not support multi-case-control comparison, unfortunately.
