### ISSUE TITLE
TypeError: NoneType object is not subscriptable, if cigarstring == *

### ISSUE THREAD

**Issue by Simarpreet-Kaur-Bhurji** [friend1ws/nanomonsv#22]
Hi team,
I was using Nanomonsv to compare control vs tumor sample. I know this tool is made for long reads, but I currently only have long reads for tumor sample and short reads for the control samples. 
The Nanomonsv parse works perfectly for the  long read tumor sample but throws the following error for the control sample:
TypeError: 'NoneType' object is not subscriptable (at parse.py line 44)
My understanding of the error is that, if the cigarstring == *, the code is not able to handle it. Can you please look into it?

**Comment by friend1ws** [comment]
Thank you very much for the report. First, I do not recommend using nanomonsv with mixed tumor and control data. But, If you send me the small BAM control files, then I will look into them.

**Comment by Simarpreet-Kaur-Bhurji** [comment]
Hi Yuichi,
Thank you for getting back to me. But I have used pysam to get rid of the
alignments where the cigarstring == * and was able to go through
the Nanomonsv pipeline successfully. However, I was wondering if you have
any recommendations for structural variation visualisation tools for the
results obtained from naomonsv?

Regards,
Simarpreet

**Comment by friend1ws** [comment]
Sorry for the late reply.
I recommend using IGV or Jbrowse2, to see the BAM file.
For interpretation of SVs such as MEI, I'm still wondering which is the best way..
