### ISSUE TITLE
Running nanomonsv with WGS samples

### ISSUE THREAD

**Issue by waltergallegog** [friend1ws/nanomonsv#23]
Hello,
I'm running nanomonsv on a tumor and control .bam files from a WGS run.
The .bam files are 63GB and 85GB respectively.

 - Have you run nanomonsv with samples of this size (or larger than 50GB)?
 - If yes, is it possible for you to share some details about the specs of the used computer, the run time required for the `parse` and `get` commands, and the RAM used? I just want to have an estimation of how much it could take in my case.
 - Is it safe if I execute two instances of `nanomonsv parse`, so I can parse both tumor and ctrl at the same time? (I mean, if the program is perhaps using temp files that could get mixed/corrupted if two instances run at the same time)

Thanks
Walter.

**Comment by friend1ws** [comment]
Sorry for the delayed response. 
> Have you run nanomonsv with samples of this size (or larger than 50GB)?
Yes.

> If yes, is it possible for you to share some details about the specs of the used computer, the run time required for the parse and get commands, and the RAM used? I just want to have an estimation of how much it could take in my case.

I believe RAM used is less than 8GB. So e.g. m5.large of AWS EC2 or m5.xlarge would be enough.

>Is it safe if I execute two instances of nanomonsv parse, so I can parse both tumor and ctrl at the same time? (I mean, if the program is perhaps using temp files that could get mixed/corrupted if two instances run at the same time)

That's would be enough if you can separate the computational environment.

**Comment by waltergallegog** [comment]
Thanks for the information, 
I was able to run nanomonsv with my WGS samples without any trouble.
