### ISSUE TITLE
nanomonsv insert_classify: Executable does not exist: minimap2

### ISSUE THREAD

**Issue by charliechen912ilovbash** [friend1ws/nanomonsv#24]
I am using v0.4.0.
My command is:
`nanomonsv insert_classify --genome_id hg38 `
and it results in:
`nanomonsv.utils - ERROR - Executable does not exist: minimap2`
But I have installed the minimap2 with conda and it can be called by `minimap2` in shell, so I am not sure which part is going wrong..

**Comment by friend1ws** [comment]
Sorry for the late response.
`nanomonsv insert_classify` calls `minimap2` through `subprocess.check_call`. So I guess it would not be a problem..
One way to check is to try simple script such as

```
# /usr/bin/env ptyhon3

import subprocess

input_fasta = sys.argv[1]
output_sam = sys.argv[2]
reference = sys.argv[3]

with open(output_sam, 'w') as hout:
    subprocess.check_call(["minimap2", "-ax", "splice", reference, input_fasta], stdout = hout)
```

And see what's happens?
