### ISSUE TITLE
circular DNA in output

### ISSUE THREAD

**Issue by charliechen912ilovbash** [friend1ws/nanomonsv#27]
Hi,
I have a simple question.
Will NanomonSV output structural variant in circular DNA like mitochondria ? (if there is a somatic SV)

**Comment by friend1ws** [comment]
Sorry for the very late response.
If the alignment was precise, then nanomonsv would identify SVs in circular DNA. 
However, I have never tried it myself.
As for mitochondria, there are polymorphisms and I think it may be quite difficult.
