### ISSUE TITLE
An error at get stage

### ISSUE THREAD

**Issue by charliechen912ilovbash** [friend1ws/nanomonsv#3]
Hi, during the 'nanomonsv get' stage, I have run the following command:

`nanomonsv get --control_prefix out/ctrl  -N --min_tumor_variant_read_num 3 --control_bam out/ctrl.bam  out/tumor out/tumor.bam  ref.fa`

and encounter this error:

```
  File "/bins/NanoFG/venv/bin/nanomonsv", line 8, in <module>
    sys.exit(main())
  File "/bins/NanoFG/venv/lib/python3.6/site-packages/nanomonsv/__init__.py", line 9, in main
    args.func(args)
  File "/bins/NanoFG/venv/lib/python3.6/site-packages/nanomonsv/run.py", line 145, in get_main
    args.tumor_prefix + ".refined_bp.txt", args.tumor_bam, args.reference_fasta, args.debug)
  File "/bins/NanoFG/venv/lib/python3.6/site-packages/nanomonsv/identify.py", line 219, in identify
    bret = get_refined_bp(tconsensus, fasta_file_ins, chr1, start1, end1, dir1, chr2, start2, end2, dir2, mode, hout_log)
  File "/bins/NanoFG/venv/lib/python3.6/site-packages/nanomonsv/identify.py", line 94, in get_refined_bp
    region_seq = fasta_file_ins.fetch(chr1, start1 - 100, end2 + 100)
  File "pysam/libcfaidx.pyx", line 290, in pysam.libcfaidx.FastaFile.fetch
  File "pysam/libcutils.pyx", line 252, in pysam.libcutils.parse_region
ValueError: start out of range (-87)
```

I have tried few times and get the same result, could you help me with this? Thank you!

**Comment by charliechen912ilovbash** [comment]
I guess this may by caused by the chromosome name after ">" in reference fasta file, I tried again only with autosome (chr1-22) and the program ended successfully.

**Comment by friend1ws** [comment]
Thank you very much for your interest in our software.
I think this is caused because the coordinate of one SV candidate is near zero and `start1 - 100`, became below zero when trying to fetch the reference sequence by 
```region_seq = fasta_file_ins.fetch(chr1, start1 - 100, end2 + 100).```
I guess your candidate includes mitochondria or virus genome sequences.
This might be avoided by changing the code to 
```region_seq = fasta_file_ins.fetch(chr1, max(0, start1 - 100), end2 + 100).```

**Comment by charliechen912ilovbash** [comment]
Yes, my original reference contain virus sequence! I see, I will try with your suggestion, thanks!

**Comment by friend1ws** [comment]
In the newer version of nanomonsv, we tried to fix the above issue. So I'm happy if you could try with the newer version.
