### ISSUE TITLE
python: src/memory.c:244: parasail_result_new_trace: Assertion `a > 0' failed.

### ISSUE THREAD

**Issue by charliechen912ilovbash** [friend1ws/nanomonsv#36]
Hello, 

I am using version 0.4.0.
During the `nanomonsv get`, it showed the following error messages.
I am using 1 thread and 192Gb memory, the normal and tumor `BAM` files are 131Gb and 81Gb, separately.
Does this mean memory is not enough?

```05/17/2023 12:47:33 - nanomonsv.run - INFO - Clustering rearrangement type supporting reads for putative SVs
05/17/2023 12:48:35 - nanomonsv.run - INFO - Clustering insertion type supporting reads for putative SVs
05/17/2023 12:48:42 - nanomonsv.run - INFO - Clustering deletion type supporting reads for putative SVs
05/17/2023 12:48:47 - nanomonsv.run - INFO - Gathering sequences of supporting reads
05/17/2023 13:47:27 - nanomonsv.run - INFO - Generate consensus sequences
python: src/memory.c:244: parasail_result_new_trace: Assertion `a > 0' failed.```

**Comment by friend1ws** [comment]
@charliechen912ilovbash Hi, did this work? I guess it happened in single breakend SV detection (--sbnd mode).

**Comment by charliechen912ilovbash** [comment]
Thank you for your reply.
I was using `FASTA` (generated by `SURVIVOR simreads`) mapped `BAM` as input, could this be the reason?
I found another read simulator that can generate `FASTQ`, and the `BAM` worked well with `NanomonSV`, so I closed the issue.

**Comment by friend1ws** [comment]
OK. Thanks.
