### ISSUE TITLE
The output of nanomonsv get

### ISSUE THREAD

**Issue by charliechen912ilovbash** [friend1ws/nanomonsv#4]
Hi, thanks for developing this program, I have few questions. 
In the output of `nanomonsv get` command, for  and example:

```
Chr_1   Pos_1   Dir_1   Chr_2   Pos_2   Dir_2   Inserted_Seq    Checked_Read_Num_Tumor  Supporting_Read_Num_Tumor       Check
ed_Read_Num_Control        Supporting_Read_Num_Control
chr1    101804934       +       chr1    102935250       +       ---     73      13      22      0
```
Since I want to know about the SV type of each line, 
if there is a sequence in the `Inserted_Seq` column, and the `Chr_1` and `Chr_2` are the same --> insertion? 
If it shows `---` in the "Inserted_Seq" column, and the `Chr_1` and `Chr_2` are the same --> deletion? 
If  the `Chr_1` and `Chr_2` are different --> translocation?

What are the types of SV can nanomonsv detect?

**Comment by charliechen912ilovbash** [comment]
Hi, I found some discussion about the strand stand for of SV,
https://github.com/hall-lab/svtools/issues/5
If this is similar to this case, which means
deletions are always +-, dups are -+ and inversions are ++ or --   ?
I will be really appreciated if someone could answer this.

**Comment by friend1ws** [comment]
Sorry for the late response. You are mostly correct. I will add a description of the classification of SV somewhere in this repository. Meanwhile, I included the script (`misc/sv_type.py`) which does essentially the same  SV classification as the bioRxiv paper.

**Comment by charliechen912ilovbash** [comment]
I understood, thanks you for providing the sv_type.py script!
