### ISSUE TITLE
intra-chromosomal translocation vs deletion/inversion

### ISSUE THREAD

**Issue by charliechen912ilovbash** [friend1ws/nanomonsv#46]
Does nanomosv distinguish intra-chromosomal translocation and deletion?
for example, if a deletion or inversion is larger than 10 mb, then there is higher chance that it is actually an intra-chromosomal translocation.

Tens of genes could be included in such large deletion/inversion. But if it is a translocation, then only the genes in breakpoints are affected. Thus, I think it is important to distinguish large deletion/inversion and intra-chromosomal translocation.

**Comment by friend1ws** [comment]
nanomonsv basically just extracts SVs as the pair of breakpoints. To distinguish intra-chromosomal translocation and deletions, you may need to see the copy number profile. We have some plans for this line of work. But it will be released as another software from nanomonsv.
