### ISSUE TITLE
simple repeat filtered result is not included in vcf output

### ISSUE THREAD

**Issue by charliechen912ilovbash** [friend1ws/nanomonsv#48]
Hello,
I am using version 0.7.0.
Is there any way to filter the vcf output with `post_filter.py` ?

**Comment by friend1ws** [comment]
Thanks!
Could you check the tutorial page?
https://github.com/friend1ws/nanomonsv/wiki/Tutorial#removing-indels-within-simple-repeat
It should work fine.

**Comment by friend1ws** [comment]
Sorry for the delay.
You may be able to use the function in nanomonsv

First, prepare the following scripts and name it as, e.g., `nanomonsv_converter.py`
```
#! /usr/bin/env python3

import sys
from nanomonsv.vcf_convert import genomesv2vcf_convert

genomesv2vcf_convert(sys.argv[1], sys.argv[2], sys.argv[3])
```

Then try the command as:
```
$ python3 nanomonsv_converter.py COLO829.nanomonsv.result.txt COLO829.nanomonsv.result.vcf ${reference_genome_path}
```

**Comment by charliechen912ilovbash** [comment]
I understood, thanks for reply.
