### ISSUE TITLE
Segmentation fault from get with NGMLR bams

### ISSUE THREAD

**Issue by shimbalama** [friend1ws/nanomonsv#5]
HI. 

nanomonsv get ran for 2.5 hrs then returned this Segmentation fault when parsing our NGMLR bams.

Do you have any idea how to trouble shoot this?

/var/spool/PBS/mom_priv/jobs/12771548.hpcpbs02.SC: line 11: 84102 Segmentation fault      (core dumped) nanomonsv get output_t/test_tumor /working/genomeinfo/share/cromwell-viewable/COLO829/tumour/call-sam1/execution/sampleID.bam /working/lab_nicw/liamM/colo829_38/get_sv_indel_reads/shasta/ref/GCA_000001405.15_GRCh38_no_alt_analysis_set.fa --control_prefix output/test_normal --control_bam /working/genomeinfo/share/cromwell-viewable/COLO829/normal/call-sam1/execution/sampleID.bam

**Comment by friend1ws** [comment]
Hi,

It seems that SSW library on which nanomonsv depends sometimes generates segmentation faults, and the author of SSW library is not very active recently. I'm considering to switch to another library. Meanwhile, in my experience, these segmentation faults can be avoided im most cases if you use docker. I'm happy if you could try nanomonsv using docker image (friend1ws/nanomonsv:0.1.2).

**Comment by friend1ws** [comment]
Hi, I will soon substitute the SSW library to another package in the next release, and hope this can solve.

**Comment by friend1ws** [comment]
We have released nanomonsv v0.2.0. This avoids the use of SSW Library and I hope this will solve your problem. So I'm happy if you could try with the newer version.

**Comment by shimbalama** [comment]
Thank you for your rapid response!

It has now run to completion on our COLO829 test sample. 

Some brief feedback:

- I was very impressed with the computational efficiency of this approach.

- nanomonsv called:
    - Most known SVs (in total it missed 16/104 known breakpoints )
    - Several new (to us) SVs
    - at least 30 germline events

Regards,
Liam

**Comment by friend1ws** [comment]
Thank you very much for the feedback. I guess germline events could be removed if you could increase the amount of control data, or if we successfully utilize the germline SV database to filter out. But please let me know if you have any additional feedback or suggestions.
