### ISSUE TITLE
Recomanded settings for Dorado basecaller

### ISSUE THREAD

**Issue by zhengzhenxian** [friend1ws/nanomonsv#50]
Hi, @friend1ws

Thanks for developing this great tool! I've come across a base quality cut-off feature for different settings (`--qv10`, `--qv15`, and `--qv20`). If I'm understanding correctly, does the` --qv20` option specifically cater to Q20+ chemistry and the Dorado basecalling?

Additionally, I've noticed that starting from version 0.7.1, there is support for duplex somatic SV calling. Does this feature also utilize the `--qv20` option?

Thanks in advance!

Zhenxian

**Comment by friend1ws** [comment]
Thanks for your interest in nanomonsv.
I think `--qv20` would be an appropriate choice for Q20+ chemistry (+ Dorado calling),
though I believe other settings (such as `--qv15` or `--qv25`) would work to some extent.

Also, `--qv20` will not cause any problems for duplex sequence data. So please try!

**Comment by zhengzhenxian** [comment]
Thanks for your prompt reply!  

I will try the option `--qv20` option first and will keep updating if I find anything interesting.
