### ISSUE TITLE
Run without matched control

### ISSUE THREAD

**Issue by charliechen912ilovbash** [friend1ws/nanomonsv#6]
Hi, in the manual page you mentioned that nanomonsv can generate a list of SVs without specifying the matched control, but when I actually run the program, the control sample seems to be required.
Can I run without the control sample?

**Comment by friend1ws** [comment]
Which version you are using? Also, could you try the Quickstart by modifying the command?
```
nanomonsv get output/test_tumor tests/resource/bam/test_tumor.bam GRCh38.d1.vd1.fa --control_prefix output/test_ctrl --control_bam tests/resource/bam/test_ctrl.bam
```
