### ISSUE TITLE
nanomonsv.parse - ERROR - query end inconsistent!!

### ISSUE THREAD

**Issue by ywzhang071394** [friend1ws/nanomonsv#68]
Hi,

Is nanomonsv not compatible for Pacbio data? I tried it and got the below error code:
 
07/10/2024 22:03:01 - nanomonsv.parse - ERROR - query end inconsistent!! m84081_240606_212430_s2/142410322/ccs: 15829 != 1971
07/10/2024 22:03:02 - nanomonsv.parse - ERROR - query end inconsistent!! m84081_240317_110233_s4/154539728/ccs: 11106 != 11071

The info of the input bam file is:
@PG	ID:pbmm2	PN:pbmm2	VN:1.13.1 (commit v1.13.1)	CL:pbmm2 align --sort -j 12 --preset HIFI --log-level DEBUG ~/data/human/t2t_chm13/pbmm2/t2t_chm13_hifi.mmi ~/projects/HTAN/longread/HT522N1_Tumor/HT522N1.merged.fq ~/projects/HTAN/longread/HT522N1_Tumor/HT522N1.aligned.bam
@PG	ID:samtools	PN:samtools	PP:pbmm2	VN:1.20	CL:samtools view -H ~/projects/HTAN/longread/HT522N1_Tumor/HT522N1.aligned.bam

Hope to get your help. Thank you so much!

**Comment by friend1ws** [comment]
Thank you very much for the interest in our software.
Currently, nanomonsv supports BAM files aligned via minimap2, and pbmm2 is not supported.
I would like to modify nanomonsv to supprot pbmm2 in the future, though.

**Comment by ajw2329** [comment]
Hello -- thanks very much for the great tool!  

Do you have any recommended settings for minimap2 with PacBio for use with nanomonsv? 

Any advice would be very much appreciated!
