### ISSUE TITLE
Run without control BAM

### ISSUE THREAD

**Issue by charliechen912ilovbash** [friend1ws/nanomonsv#7]
Hi, 

I tried to run the `nanomonsv get` without control sample like following with the newest version:
`nanomonsv get   out/sample-T  tumor.bam  ref.fa`

But it seems that control group is required:
`nanomonsv get: error: the following arguments are required: --control_prefix, --control_bam`

**Comment by friend1ws** [comment]
Hi,

In our environment, I could successfully run the ``nanomonsv get`` command without control options. Could you show me the version you are using?

```
nanomonsv --version
```

**Comment by charliechen912ilovbash** [comment]
Hi,

I am using 0.2.0. I just confirm again, it seems work well with only control sample!
I probably mistyped some commands last time.
Thank you!

**Comment by friend1ws** [comment]
Great!
