### ISSUE TITLE
The compatibility with lra aligner

### ISSUE THREAD

**Issue by charliechen912ilovbash** [friend1ws/nanomonsv#8]
Hi,

Recently I am wondering about the compatibility between NanomonSV and lately released aligner lra:
https://www.biorxiv.org/content/10.1101/2020.11.15.383273v1.full
https://github.com/ChaissonLab/LRA
Is it better than minimap2-NanomonSV combination?

Charlie

**Comment by friend1ws** [comment]
I have not performed yet. I'm aware that nanomonsv + minimap2 and nanomonsv + NGMLR work fine. I may do experiments (I'm also interested in trying Winnowmap). But I greatly welcome your feedback when you try it.
